apiVersion: v2
name: metafunction
description: A Helm chart for MetaFunction production deployment
type: application
version: 1.0.0
appVersion: "2.0.0"
keywords:
  - metafunction
  - ai
  - research
  - papers
home: https://metafunction.com
sources:
  - https://github.com/your-org/metafunction
maintainers:
  - name: MetaFunction Team
    email: team@metafunction.com
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
icon: https://metafunction.com/icon.png
