# Horizontal Pod Autoscaler for MetaFunction
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metafunction-hpa
  namespace: metafunction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metafunction
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metafunction-pdb
  namespace: metafunction
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: metafunction
