apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metafunction.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metafunction.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc }}
  deepseek-api-key: {{ .Values.secrets.deepseekApiKey | b64enc }}
  perplexity-api-key: {{ .Values.secrets.perplexityApiKey | b64enc }}
  database-url: {{ printf "postgresql://metafunction_user:%s@%s-postgresql:5432/metafunction" .Values.secrets.databasePassword .Release.Name | b64enc }}
